### ISSUE TITLE
ProjectInitializer crashing after first use

### ISSUE THREAD

**Issue by CodeHelix** [fehaar/FFWD-Templates#2] opened 2012-03-11 03:03 UTC
The ProjectInitializer worked the first time I used but when I try to make another project with a different name or delete the one I did make and create another one with the same name it will crash. Here is the exception error I get when I debug it:

System.IO.IOException was unhandled
  HResult=-2147024816
  Message=The file 'XNA\Test.suo' already exists.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
       at System.IO.File.Copy(String sourceFileName, String destFileName)
       at ProjectInitializer.Program.CopyContents(String dir, String newDir)
       at ProjectInitializer.Program.Execute()
       at ProjectInitializer.Program.Main(String[] args)
  InnerException: 

The thing is Test.suo doesn't exist and I get the same exact error even when I type in a different name for the project.

**Comment by fehaar** [comment] 2012-03-12 13:11
I have looked at the ProjectInitializer and added some more error handling. I have also told it to ignore suo files. The file is probably there, but it is hidden. So unless you show hidden files and folders in your explorer, you will not see it.

**Comment by CodeHelix** [comment] 2012-03-12 17:18
Thanks for looking into this. I get the same error still when trying to create new projects with different names but if I remove the one I was able to create from the XNA folder then it will create a new one.

For an example I name my first one Test and it successfully creates it.
I then go and try and make another one called CodeHelix which will be unsuccessful and will say that Test.suo already exists and crash.

For some reason it will keep looking at the name of the first one created until it is removed from the XNA folder which is what I plan to do anyways but thought I'd let you know about this.

**Comment by Elideb** [comment] 2012-03-12 19:17
The problem is that Directory.EnumerateFiles looks for the next file lazily. This can cause the following problem:
1- EnumerateFiles returns FFWD.Template.sln
2- FFWD.Template.sln renamed to Test.sln
3- EnumerateFiles returns FFWD.Template.suo
4- FFWD.Template.suo renamed to Test.suo
5- EnumerateFiles returns Test.sln
6- IOException trying to copy Test.sln to Test.sln

I'm intrigued, because this happens consistently in only one of the three computers I've run the Initializer on, but never in the other two. It might be a minor change in behaviour in a recent .NET version or something related to FAT32 drives. Those are the only things I can think of.

I've submitted a fix to my fork of FFWD (the framework, not the template) and it is pending review by feehar. If you are in a hurry, you can check it out and fix the issue yourself.
Elideb/FFWD@5439c4791c75c8c5897f85ffd78c6167464b9fa9

**Comment by fehaar** [comment] 2012-03-12 19:44
Ah... Lazy evaluation of files. Yeah. In these Async days it makes sense. I hadn't seen that one coming. I have merged the request, so it should be working now.

**Closed as completed by fehaar** 2012-03-12 19:44 UTC
